project:
  type: website
  output-dir: _build

metadata-files:
  - api/_sidebar.yml

filters:
  - interlinks

interlinks:
  fast: true
  sources:
    numpy:
      url: https://numpy.org/doc/stable/
    python:
      url: https://docs.python.org/3/

website:
  title: "targeter"
  page-navigation: true
  navbar:
    left:
      - file: get-started/overview.qmd
        text: Get Started
    right:
      - icon: github
        href: https://github.com/welovedatascience/py-targeter/
  sidebar:
    - id: get-started
      title: Get Started
      style: floating
      align: left
      contents:
        - get-started/overview.qmd
        - section: "Basic Use"
          contents:
            - get-started/basic-docs.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


quartodoc:
  style: pkgdown
  dir: api
  package: targeter
  render_interlinks: true
  sidebar: "api/_sidebar.yml"
  sections:
    - title: Preparation Functions
      desc: |
        These functions fetch and analyze Python objects, including parsing docstrings.
        They prepare a basic representation of your doc site that can be rendered and built.
      contents:
        - targeter.Targeter
